import { AppHeader, AppSidebar } from '../components';
import './global.css';

export const metadata = {
  title: 'Halcyon Playground',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <AppHeader />
        <div className="flex-1 flex items-stretch">
          <AppSidebar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
